In [20]:
from tqdm import tqdm
import numpy as np
import pandas as pd
from itertools import accumulate
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import scale, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix
from sklearn.feature_selection import f_classif
from sklearn.utils import resample

# to supress warnings
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

sns.set_context('notebook')
sns.set_style('white')



In [2]:
df = pd.read_excel('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/X4i8vXLw81g4wEH473zIFA/Diabetes-Classification.xlsx')

In [3]:
df.head()

Patient number  Cholesterol  Glucose  HDL Chol  Chol/HDL ratio  Age  \
0               1          193       77        49             3.9   19   
1               2          146       79        41             3.6   19   
2               3          217       75        54             4.0   20   
3               4          226       97        70             3.2   20   
4               5          164       91        67             2.4   20   

   Gender  Height  Weight   BMI  Systolic BP  Diastolic BP  waist  hip  \
0  female      61     119  22.5          118            70     32   38   
1  female      60     135  26.4          108            58     33   40   
2  female      67     187  29.3          110            72     40   45   
3  female      64     114  19.6          122            64     31   39   
4  female      70     141  20.2          122            86     32   39   

   Waist/hip ratio     Diabetes  Unnamed: 16  Unnamed: 17  
0             0.84  No diabetes          6.0          6.0  
1             0.83  No diabetes          NaN          NaN  
2             0.89  No diabetes          NaN          NaN  
3             0.79  No diabetes          NaN          NaN  
4             0.82  No diabetes          NaN          NaN

In [4]:
# last columns are not nescessary, hence dropping those
df.drop(columns=['Unnamed: 16', 'Unnamed: 17'])
df.columns

Index(['Patient number', 'Cholesterol', 'Glucose', 'HDL Chol',
       'Chol/HDL ratio', 'Age', 'Gender', 'Height', 'Weight', 'BMI',
       'Systolic BP', 'Diastolic BP', 'waist', 'hip', 'Waist/hip ratio',
       'Diabetes', 'Unnamed: 16', 'Unnamed: 17'],
      dtype='object')

In [5]:
# before analysing seeing what proportion of patient have diabetes and not
frequency_table = df['Diabetes'].value_counts(); #returns count of unique values
props = frequency_table.apply(lambda x: x/len(df['Diabetes']))
print(props)

Diabetes
No diabetes    0.846154
Diabetes       0.153846
Name: count, dtype: float64


In [6]:
# reducing becoz we're going to compute using thies fields only
attributes_required = ['Diabetes', 'Cholesterol', 'Glucose','BMI', 'Waist/hip ratio', 'HDL Chol', 'Chol/HDL ratio', 'Systolic BP', 'Diastolic BP', 'Weight' ]
df_reduced = df[attributes_required]

df_reduced.head()

Diabetes  Cholesterol  Glucose   BMI  Waist/hip ratio  HDL Chol  \
0  No diabetes          193       77  22.5             0.84        49   
1  No diabetes          146       79  26.4             0.83        41   
2  No diabetes          217       75  29.3             0.89        54   
3  No diabetes          226       97  19.6             0.79        70   
4  No diabetes          164       91  20.2             0.82        67   

   Chol/HDL ratio  Systolic BP  Diastolic BP  Weight  
0             3.9          118            70     119  
1             3.6          108            58     135  
2             4.0          110            72     187  
3             3.2          122            64     114  
4             2.4          122            86     141

In [7]:
# diabetes is target column (type is string in this case)
# hence filter only numeric cols for applying scaling
numerical_columns = df_reduced.iloc[:, 1:10]
numerical_columns

Cholesterol  Glucose   BMI  Waist/hip ratio  HDL Chol  Chol/HDL ratio  \
0            193       77  22.5             0.84        49             3.9   
1            146       79  26.4             0.83        41             3.6   
2            217       75  29.3             0.89        54             4.0   
3            226       97  19.6             0.79        70             3.2   
4            164       91  20.2             0.82        67             2.4   
..           ...      ...   ...              ...       ...             ...   
385          227      105  25.2             0.88        44             5.2   
386          226      279  37.5             0.85        52             4.3   
387          301       90  21.7             0.76       118             2.6   
388          232      184  24.0             0.92       114             2.0   
389          165       94  39.7             1.00        69             2.4   

     Systolic BP  Diastolic BP  Weight  
0            118            70     119  
1            108            58     135  
2            110            72     187  
3            122            64     114  
4            122            86     141  
..           ...           ...     ...  
385          150            90     125  
386          144            88     192  
387          218            90     115  
388          170            82     127  
389          160            82     217  

[390 rows x 9 columns]

In [8]:
# use of StandardScaler is to scale the data to reduce the impact of extreme values
# apply scaler
scaler = StandardScaler()
preproc_reduced = scaler.fit(numerical_columns)
# preproc_reduced is a StandardScaler Object
# fit method returns a StandardScaler Object

In [9]:
df_standardized = preproc_reduced.transform(numerical_columns)
# transform returns a ndarray or spmatrix
# main parameter - a matrix like object (like StandardScaler())
df_standardized


array([[-0.31901328, -0.5646553 , -0.95194412, ..., -0.83807114,
        -0.98582201, -1.44731175],
       [-1.37261932, -0.52743157, -0.36035801, ..., -1.27608741,
        -1.87597193, -1.05084021],
       [ 0.21899831, -0.60187902,  0.07953936, ..., -1.18848416,
        -0.83746369,  0.23769232],
       ...,
       [ 2.10203888, -0.32270108, -1.07329512, ...,  3.54209161,
         0.49776118, -1.54642964],
       [ 0.55525555,  1.42681407, -0.724411  , ...,  1.43961349,
        -0.0956721 , -1.24907598],
       [-0.94669348, -0.24825362,  1.65710232, ...,  1.00159722,
        -0.0956721 ,  0.98107646]])

In [10]:
# converting the ndarray to pandas dataframe
df_standardized = pd.DataFrame(df_standardized, columns=numerical_columns.columns)
# Dataframe method takes 2 params, one is an Iterable Object, second is columns indexes
df_standardized.head()

Cholesterol   Glucose       BMI  Waist/hip ratio  HDL Chol  Chol/HDL ratio  \
0    -0.319013 -0.564655 -0.951944        -0.565995 -0.073401       -0.360132   
1    -1.372619 -0.527432 -0.360358        -0.702760 -0.536983       -0.533102   
2     0.218998 -0.601879  0.079539         0.117828  0.216339       -0.302476   
3     0.420753 -0.192418 -1.391841        -1.249818  1.143504       -0.763729   
4    -0.969111 -0.304089 -1.300828        -0.839524  0.969660       -1.224982   

   Systolic BP  Diastolic BP    Weight  
0    -0.838071     -0.985822 -1.447312  
1    -1.276087     -1.875972 -1.050840  
2    -1.188484     -0.837464  0.237692  
3    -0.662865     -1.430897 -1.571209  
4    -0.662865      0.201045 -0.902163

In [11]:
# concatatenating the removed col before applying scaler
df_stize = pd.concat([df_reduced['Diabetes'], df_standardized], axis=1)
df_stize

Diabetes  Cholesterol   Glucose       BMI  Waist/hip ratio  HDL Chol  \
0    No diabetes    -0.319013 -0.564655 -0.951944        -0.565995 -0.073401   
1    No diabetes    -1.372619 -0.527432 -0.360358        -0.702760 -0.536983   
2    No diabetes     0.218998 -0.601879  0.079539         0.117828  0.216339   
3    No diabetes     0.420753 -0.192418 -1.391841        -1.249818  1.143504   
4    No diabetes    -0.969111 -0.304089 -1.300828        -0.839524  0.969660   
..           ...          ...       ...       ...              ...       ...   
385  No diabetes     0.443170 -0.043523 -0.542385        -0.018937 -0.363140   
386     Diabetes     0.420753  3.194941  1.323387        -0.429231  0.100443   
387  No diabetes     2.102039 -0.322701 -1.073295        -1.660112  3.924999   
388     Diabetes     0.555256  1.426814 -0.724411         0.528122  3.693208   
389  No diabetes    -0.946693 -0.248254  1.657102         1.622239  1.085556   

     Chol/HDL ratio  Systolic BP  Diastolic BP    Weight  
0         -0.360132    -0.838071     -0.985822 -1.447312  
1         -0.533102    -1.276087     -1.875972 -1.050840  
2         -0.302476    -1.188484     -0.837464  0.237692  
3         -0.763729    -0.662865     -1.430897 -1.571209  
4         -1.224982    -0.662865      0.201045 -0.902163  
..              ...          ...           ...       ...  
385        0.389404     0.563581      0.497761 -1.298635  
386       -0.129506     0.300771      0.349403  0.361590  
387       -1.109668     3.542092      0.497761 -1.546430  
388       -1.455608     1.439613     -0.095672 -1.249076  
389       -1.224982     1.001597     -0.095672  0.981076  

[390 rows x 10 columns]

In [12]:
# split the dataset now
# X will have all attributes but target(predictors)
# y will have only Diabetes attribute (target)
X = df_stize.drop(columns=['Diabetes'])
y = df_stize['Diabetes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# encoding target variable from string to numerical (0 or 1)
# becoz KNN requires numerical input

# Initialize LabelEncoder
label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.fit_transform(y_test)

# fit_transform takes a arraylike param and returns ndarray (encoded)


In [14]:
# creating the knn model
knn = KNeighborsClassifier()
# fit the knn model
knn.fit(X_train, y_train_encoded)
# after fitting , predicting the target using test dataset
y_pred = knn.predict(X_test)
# calculate overall accuracy by comparing below two
accuracy = accuracy_score(y_test_encoded, y_pred)
print(f'Accuracy: {accuracy:.2%}')
# i got 88.46% yours will differ


Accuracy: 88.46%


In [15]:
# lets see if we can work on tuning to improve accuracy
# hyperparameter tuning
# in this case the hyperparameter is number of neighbors

knn = KNeighborsClassifier()

param_grid = {'n_neighbors': range(1,12)}
param_grid # it is a dict we are gonna use

{'n_neighbors': range(1, 12)}

## GridSearchCV:

GridSearchCV is a function in the sklearn library that performs an exhaustive search over a specified parameter grid for an estimator (in this case, the K-Nearest Neighbors model knn).
It trains the model for every combination of the provided parameters and evaluates it using cross-validation to find the best combination of hyperparameters.

### expalining the parameters passed

##### knn:

This is the machine learning model you are trying to tune, which in this case is likely a K-Nearest Neighbors (KNN) classifier or regressor.


##### param_grid:

This is a dictionary or a list of dictionaries where the keys are the hyperparameter names, and the values are the lists of settings to be tested. For example:
python

param_grid = {
    'n_neighbors': [3, 5, 7],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}
GridSearchCV will test all possible combinations of these hyperparameters.


##### cv=10:

cv stands for cross-validation. Setting cv=10 means that the grid search will use 10-fold cross-validation. This means that the dataset will be split into 10 parts (folds), and for each combination of parameters, the model will be trained on 9 folds and tested on the 10th. This process is repeated 10 times, with each fold being used as the test set once.

In [16]:
#performing grid search with cross validation
grid_search = GridSearchCV(knn,param_grid,cv=10)
# grid_search is a GridSearchCV object

In [17]:
#fitting the hyperparameters after cross-validation
grid_search.fit(X_train, y_train_encoded)


GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 12)})

In [18]:
print("Best params found", grid_search.best_params_)
print(f"Best accuracy score: , {grid_search.best_score_:.3f}")

# best_params_ is an dict and best_score_ is a float
# i got n_neighbors = 7 as my best hence my k value is 7

Best params found {'n_neighbors': 7}
Best accuracy score: , 0.917


In [19]:
# full results
results = grid_search.cv_results_

for mean_score, std_score, params in zip(results['mean_test_score'],results['std_test_score'], results['params']):
    print(f"Mean accuracy: {mean_score:.3f} (std: {std_score:.3f}) with: {params}")

Mean accuracy: 0.875 (std: 0.053) with: {'n_neighbors': 1}
Mean accuracy: 0.820 (std: 0.047) with: {'n_neighbors': 2}
Mean accuracy: 0.901 (std: 0.037) with: {'n_neighbors': 3}
Mean accuracy: 0.897 (std: 0.038) with: {'n_neighbors': 4}
Mean accuracy: 0.913 (std: 0.038) with: {'n_neighbors': 5}
Mean accuracy: 0.913 (std: 0.038) with: {'n_neighbors': 6}
Mean accuracy: 0.917 (std: 0.043) with: {'n_neighbors': 7}
Mean accuracy: 0.917 (std: 0.043) with: {'n_neighbors': 8}
Mean accuracy: 0.917 (std: 0.036) with: {'n_neighbors': 9}
Mean accuracy: 0.917 (std: 0.036) with: {'n_neighbors': 10}
Mean accuracy: 0.913 (std: 0.038) with: {'n_neighbors': 11}


# ANOVA for feature selection
In this section, you'll see which features are the most important when classifying patients. ANOVA, which stands for Analysis of Variance, is a statistical method that is used to compare means across multiple groups to determine if there are any statistically significant differences between the means of these groups (glucose, cholesterol, weight, BMI, and so on). 

#### It assumes that there are no differences between the group means, and results from the hypothesis testing will tell you whether or a specific feature is significant.

In [25]:
# ANOVA - Analysis of Variance

fs_score , fs_p_value = f_classif(X, y)
# f_classif returns a tuple
# takes X-matrixlike, and y - any, as params
fs_score, fs_p_value
# fs stands for feature selection

# f_classif method returns the importance of every 
# attribute as scores by calculating variance

(array([ 16.89337992, 350.80917739,   8.3650553 ,  12.34808313,
          5.97335529,  31.24267843,  15.93179469,   0.94729192,
         10.58845382]),
 array([4.82735305e-05, 3.20511866e-56, 4.04051187e-03, 4.93503790e-04,
        1.49681160e-02, 4.29811469e-08, 7.85302358e-05, 3.31015954e-01,
        1.23774938e-03]))

In [30]:
# combine scores with feature names
fs_scores = pd.DataFrame({'Feature': X.columns, 'F-Score': fs_score, 'P-Value': fs_p_value})

print(fs_scores)
print("\n After Sorting")

fs_scores = fs_scores.sort_values(by='F-Score', ascending=False)

print(fs_scores)

# P-value is defined as the measure of 
# the probability that an observed difference 
# might have occurred just by random chance.

# p value should be lower, f score should be higher
# for feature selection

           Feature     F-Score       P-Value
0      Cholesterol   16.893380  4.827353e-05
1          Glucose  350.809177  3.205119e-56
2              BMI    8.365055  4.040512e-03
3  Waist/hip ratio   12.348083  4.935038e-04
4         HDL Chol    5.973355  1.496812e-02
5   Chol/HDL ratio   31.242678  4.298115e-08
6      Systolic BP   15.931795  7.853024e-05
7     Diastolic BP    0.947292  3.310160e-01
8           Weight   10.588454  1.237749e-03

 After Sorting
           Feature     F-Score       P-Value
1          Glucose  350.809177  3.205119e-56
5   Chol/HDL ratio   31.242678  4.298115e-08
0      Cholesterol   16.893380  4.827353e-05
6      Systolic BP   15.931795  7.853024e-05
3  Waist/hip ratio   12.348083  4.935038e-04
8           Weight   10.588454  1.237749e-03
2              BMI    8.365055  4.040512e-03
4         HDL Chol    5.973355  1.496812e-02
7     Diastolic BP    0.947292  3.310160e-01


You'll do two things here to improve your performance:

1. You'll balance your data set so that you have equal numbers of records with and without diabetes. (downsampling)

2. You'll see how you do when you use just the Glucose readings to calculate the distance to your 'neighbors' in KNN.

# Downsampling
Downsampling is a common data processing technique that addresses imbalances in a dataset by removing data from the majority class such that it matches the size of the minority class.

In [31]:
# Downsampling the data

# converting diabetes column into binary(0 for negative 1 for positive)
df_stize['Diabetes'] = np.where(df_stize['Diabetes'] == 'Diabetes', 1, 0)
df_stize

Diabetes  Cholesterol   Glucose       BMI  Waist/hip ratio  HDL Chol  \
0           0    -0.319013 -0.564655 -0.951944        -0.565995 -0.073401   
1           0    -1.372619 -0.527432 -0.360358        -0.702760 -0.536983   
2           0     0.218998 -0.601879  0.079539         0.117828  0.216339   
3           0     0.420753 -0.192418 -1.391841        -1.249818  1.143504   
4           0    -0.969111 -0.304089 -1.300828        -0.839524  0.969660   
..        ...          ...       ...       ...              ...       ...   
385         0     0.443170 -0.043523 -0.542385        -0.018937 -0.363140   
386         1     0.420753  3.194941  1.323387        -0.429231  0.100443   
387         0     2.102039 -0.322701 -1.073295        -1.660112  3.924999   
388         1     0.555256  1.426814 -0.724411         0.528122  3.693208   
389         0    -0.946693 -0.248254  1.657102         1.622239  1.085556   

     Chol/HDL ratio  Systolic BP  Diastolic BP    Weight  
0         -0.360132    -0.838071     -0.985822 -1.447312  
1         -0.533102    -1.276087     -1.875972 -1.050840  
2         -0.302476    -1.188484     -0.837464  0.237692  
3         -0.763729    -0.662865     -1.430897 -1.571209  
4         -1.224982    -0.662865      0.201045 -0.902163  
..              ...          ...           ...       ...  
385        0.389404     0.563581      0.497761 -1.298635  
386       -0.129506     0.300771      0.349403  0.361590  
387       -1.109668     3.542092      0.497761 -1.546430  
388       -1.455608     1.439613     -0.095672 -1.249076  
389       -1.224982     1.001597     -0.095672  0.981076  

[390 rows x 10 columns]

In [35]:
# Number of rows for positive diabetes
positive_diabetes = df_stize[df_stize['Diabetes'] == 1].shape[0]
print('Number of rows for positive diabetes: ', positive_diabetes)

# look what the .shape[0] attribute did

Number of rows for positive diabetes:  60


In [41]:
# sample negative cases to match positive cases
negative_diabetes = df_stize[df_stize['Diabetes']==0]
print(negative_diabetes)


# resample returns a list
#resample(
#     *arrays: Any,
#     replace: bool = True,
#     n_samples: Int | None = None,
#     random_state: Int | None = None,
#     stratify: MatrixLike | None = None
# ) -> (list | None)
negative_diabetes_downsampled = resample(negative_diabetes, replace=False, n_samples=positive_diabetes, random_state=42)



     Diabetes  Cholesterol   Glucose       BMI  Waist/hip ratio  HDL Chol  \
0           0    -0.319013 -0.564655 -0.951944        -0.565995 -0.073401   
1           0    -1.372619 -0.527432 -0.360358        -0.702760 -0.536983   
2           0     0.218998 -0.601879  0.079539         0.117828  0.216339   
3           0     0.420753 -0.192418 -1.391841        -1.249818  1.143504   
4           0    -0.969111 -0.304089 -1.300828        -0.839524  0.969660   
..        ...          ...       ...       ...              ...       ...   
383         0     0.734593 -0.359925  0.200890         0.117828 -0.073401   
384         0     1.070850  0.086760 -0.375527        -0.292466 -0.942618   
385         0     0.443170 -0.043523 -0.542385        -0.018937 -0.363140   
387         0     2.102039 -0.322701 -1.073295        -1.660112  3.924999   
389         0    -0.946693 -0.248254  1.657102         1.622239  1.085556   

     Chol/HDL ratio  Systolic BP  Diastolic BP    Weight  
0         -0.360

In [46]:
# put positive and negative diabetes case into one DF -> blalanced
balanced = pd.concat([negative_diabetes_downsampled, df_stize[df_stize['Diabetes']==1]])
balanced.sample(5) # returns 5 random records

Diabetes  Cholesterol   Glucose       BMI  Waist/hip ratio  HDL Chol  \
310         1     0.622507  0.030924  3.431861         0.117828  0.506078   
322         1     3.021142  2.673809  0.701463         1.348710 -0.131348   
43          0     0.689758 -0.601879  0.671125        -0.429231 -0.826722   
174         0    -0.677688 -0.117971  0.034033         0.664887 -0.826722   
305         1     0.084495  2.189900 -0.496878         0.938416 -1.232357   

     Chol/HDL ratio  Systolic BP  Diastolic BP    Weight  
310       -0.302476     1.658622     -0.244030  2.789978  
322        1.484880     1.790027      0.349403  0.584605  
43         1.196597    -0.312452     -0.244030 -0.183559  
174        0.216434     0.388374      0.794478 -0.084441  
305        1.600193     2.315646      1.239553 -0.827825

In [47]:
# check whether both classes are balanced
balanced['Diabetes'].value_counts()


Diabetes
0    60
1    60
Name: count, dtype: int64

In [68]:
# fitting on simpler model
# we are only using glucose attrib as predictor
X_simple = balanced[['Glucose']]
y_simple = balanced['Diabetes']

#split the data
X_train_simple, X_test_simple, y_train_simple, y_test_simple = train_test_split(X_simple, y_simple, test_size=0.2, random_state=42)


Index(['Glucose'], dtype='object')

In [75]:
knn_simple = KNeighborsClassifier()

# .reshape works on 2d arrays only
X_train_simple_2d = np.array(X_train_simple['Glucose'])
X_test_simple_2d = np.array(X_test_simple['Glucose'])
# here it'll be rows

# reshaping df since it has one feature only
X_train_simple_2d = X_train_simple_2d.reshape(-1, 1)
X_test_simple_2d = X_test_simple_2d.reshape(-1, 1)
# here it'll be columns

X_train_simple_2d

# you might get a value error since only one feature is used
# you must reshape the df because of this reason
# Reshape your data either using array.
# reshape(-1, 1) if your data has a single feature 
# or array.reshape(1, -1) if it contains a single sample.

array([[-0.43437226],
       [-0.28547735],
       [-0.95550443],
       [ 4.36748847],
       [ 1.38959035],
       [ 0.7009514 ],
       [-0.54604343],
       [ 0.23565482],
       [-0.39714853],
       [ 1.83627506],
       [-0.28547735],
       [ 1.78043947],
       [-0.47159598],
       [-0.5646553 ],
       [ 3.19494108],
       [-0.30408921],
       [-0.54604343],
       [-0.54604343],
       [ 0.23565482],
       [-0.47159598],
       [ 0.21704296],
       [ 2.45046655],
       [ 0.347326  ],
       [ 3.02743431],
       [ 0.42177346],
       [-0.62049089],
       [-0.28547735],
       [-0.02491126],
       [ 0.42177346],
       [ 2.24573606],
       [ 0.38454973],
       [ 2.87853941],
       [-0.28547735],
       [-0.41576039],
       [ 2.33879537],
       [ 1.48264966],
       [ 1.83627506],
       [ 0.10537178],
       [-0.13658244],
       [ 0.03092433],
       [ 1.29653103],
       [ 0.44038532],
       [-0.2110299 ],
       [ 1.27791917],
       [-0.84383325],
       [-0

In [76]:
knn_simple.fit(X_train_simple_2d, y_train_simple)
y_pred_simple = knn_simple.predict(X_test_simple)

accuracy_simple = accuracy_score(y_test_simple, y_pred_simple)

print(f'Accuracy only using Glucose: {accuracy_simple:.2%}')

Accuracy only using Glucose: 91.67%


In [77]:
# evaluating KNN

# evaluate confusion matrix
cm = confusion_matrix(y_test_encoded, y_pred)
print("Confusion Matrix: ")
print(cm)
print(f'Accuracy from 1st model using all attributes: {accuracy:.2%}')

Confusion Matrix: 
[[ 8  8]
 [ 1 61]]
Accuracy from 1st model using all attributes: 88.46%
